services:
  postgres:
    image: postgres:16-alpine
    container_name: resto_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: resto_db
      POSTGRES_USER: resto_user
      POSTGRES_PASSWORD: resto_secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
