[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_WEBPACK = "true"
  NEXT_PUBLIC_API_URL = "https://resto-h-api.onrender.com/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers CORS/sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
