services:
  - type: web
    name: sgrh-api
    runtime: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Resto-H
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: FRONTEND_URL
        sync: false
      - key: SANCTUM_STATEFUL_DOMAINS
        sync: false
      - key: BCRYPT_ROUNDS
        value: "12"
